name: CI-CodeBuild 🚀

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on:
      - codebuild-<project name>-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Test Command
        run: ls
